services:
  - type: web
    name: contract-generator-dmg
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: generator-data
      mountPath: /opt/render/project/src/generated
      sizeGB: 1
